version: '3.8'

services:
  odoo:
    image: odoo:16.0
    container_name: odoo
    depends_on:
      - db
    ports:
      - 8069:8069
    networks:
      - odoo-network
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1 # for windows
    volumes:
      - odoo-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
    logging:                    # Add logging configuration here
      options:
        max-size: 10m
    command: $OPTIONS --dev=qweb,xml
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: db
    ports:
      - 5431:5432
    networks:
      - odoo-network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    logging:                    # Add logging configuration here
      options:
        max-size: 10m

volumes:
  odoo-data:
  odoo-addons:
  db-data:

networks:
  odoo-network:
